### ISSUE TITLE
Problem to boot on b450, r5 2600

### ISSUE THREAD

**Issue by demokrrat** [mikigal/ryzen-hackintosh#21]
Hello, please help me understand where these errors come from https://prnt.sc/119q0fk. And on any config the same thing. There is also such a problem with the network card https://prnt.sc/11acft2

Config of the problem computer
_Ryzen 5 2600. Asrock b450m pro4. 16gb ddr4 3200mhz. Xfx rx 590 fatboy._

The same efi-config started up immediately without problems on
_Ryzen 7 2700. Asrock b450m pro4. 16gb ddr4 3200mhz. Sapphire rx 580_

**Comment by mikigal** [comment]
Hi,
Dortania guide says this about XFX cards:
`The only brand of GPU you should avoid with the Polaris series would be XFX, PowerColour, HIS and VisionTek as many users have had issues with these cards with viewing Clover and macOS booting but other users have found fixes/workarounds(though nothing consistent). This seems to be caused by having an odd VBIOS that doesn't communicate well with macOS and the only real solution is flashing another VBIOS which is not ideal for most users.` 

I'm not sure, but it looks like GPU issue, I don't know how to help you.
Ask on AMD-OSX Discord, there someone more advanced should know how to help you.
https://discord.com/invite/EfCYAJW
