### ISSUE TITLE
Unable to receive updates

### ISSUE THREAD

**Issue by kristinaking** [mikigal/ryzen-hackintosh#35]
It's my OC config. What's the problem

**Comment by mikigal** [comment]
Since Monterey updating is in general a complicated process. Since Beta 6 you must set SecureBootModel in your config to j137 if you use iMacPro1,1 or j160 if you use MacPro7,1. When you set it, then start downloading update and instantly set it to Disabled again, you must do it before it start updating.

On Beta 7 there's additional step needed - first update stage (booting from Macintosh HD volume) must be done on iMac17,1 (e. g. from second OpenCore on pendrive). After first reboot you must back to your original SMBIOS.

It's not known if it will be needed in the future, we even don't know why iMac17,1 method works.

**Comment by kristinaking** [comment]
Thank you for your explanation

**Comment by kristinaking** [comment]
I tried, but it didn't work

**Comment by mikigal** [comment]
I thought that you already installed Beta Profile. For Public Beta you can get it from Apple's website, for Developer Beta use https://betaprofiles.com or Seeding.framework method. Even with installed profile you may have issues with updating Monterey, if you have any problems try method described above.

**Comment by kristinaking** [comment]
I did the beta 6 installation on the U disk. Is this equivalent to no beta profile

**Comment by kristinaking** [comment]
However, the software update prompts that this MAC has been registered in the apple development seed program

**Comment by mikigal** [comment]
It's okey. If you don't see Beta 7 update (it was released yesterday) you have to use method described above.

**Comment by kristinaking** [comment]
OK, thank you
