### ISSUE TITLE
cpuid_cores_per_package not containing B8 00 0000 0000 but uAAAAAAA

### ISSUE THREAD

**Issue by Entretoize** [mikigal/ryzen-hackintosh#59]
You tell to replace B8 00 0000 0000 by B8 08 0000 0000 for a eigth core processor in the replace key of cpuid_cores_per_package but in your config.plist the value is uAAAAAAA (for the first one), so I don't understand if it's really in that file or if there's something I'm missing.

**Comment by mikigal** [comment]
Values in OpenCore's config are stored in Base64 format.
As you can see `uAAAAAAA` in Base64 is `B8 00 0000 0000` in HEX (look at screenshot).
Use for example ProperTree tool, which allow to edit config in GUI, not as text file. This tool automatically allow you to modify values in hex instead of base64

![base64](https://user-images.githubusercontent.com/10632503/233794709-8cb5d3db-0824-4524-a1b1-43b4cf32a6a2.png)

**Comment by Entretoize** [comment]
Oh yes, sorry.
thanks !
